Change directories not using ERP_DIR variable

diff --git a/mpris-rpc b/mpris-rpc
--- a/mpris-rpc
+++ b/mpris-rpc
@@ -8,23 +8,23 @@
 export ERP_DIR="$HOME/.local/share/mpris-rpc"
 # function to create directory and download EasyRP if does not exist
 geteasyrp() {
-    if [[ ! -d "$HOME/.local/share/mpris-rpc" || ! -f "$HOME/.local/share/mpris-rpc/easyrp" ]]; then
-        echo "EasyRP not found in '$HOME/.local/share/mpris-rpc'. Downloading now..."
-        rm -rf "$HOME"/.local/share/mpris-rpc
-        mkdir -p "$HOME"/.local/share/mpris-rpc
+    if [[ ! -d "$ERP_DIR" || ! -f "$ERP_DIR/easyrp" ]]; then
+        echo "EasyRP not found in '$ERP_DIR'. Downloading now..."
+        rm -rf "$ERP_DIR"
+        mkdir -p "$ERP_DIR"
         mkdir -p "$HOME"/.cache
         curl -sL "https://github.com/Pizzabelly/EasyRP/releases/download/v3.0/EasyRP-v3.0-linux.tar.gz" -o "$HOME"/.cache/EasyRP-linux.tar.gz || \
         { echo "EasyRP download failed!"; exit 1; }
-        cd "$HOME"/.local/share/mpris-rpc
-        tar xzf "$HOME"/.cache/EasyRP-linux.tar.gz -C "$HOME"/.local/share/mpris-rpc || { echo "Failed to extract EasyRP!"; exit 1; }
-        mv "$HOME"/.local/share/mpris-rpc/EasyRP-v3.0-linux/* "$HOME"/.local/share/mpris-rpc/
-        rm -rf "$HOME"/.local/share/mpris-rpc/EasyRP-v3.0-linux
+        cd "$ERP_DIR"
+        tar xzf "$HOME"/.cache/EasyRP-linux.tar.gz -C "$ERP_DIR" || { echo "Failed to extract EasyRP!"; exit 1; }
+        mv "$ERP_DIR"/EasyRP-v3.0-linux/* "$ERP_DIR"/
+        rm -rf "$ERP_DIR"/EasyRP-v3.0-linux
         rm -f "$HOME"/.cache/EasyRP-linux.tar.gz
-        if [[ ! -f "$HOME/.local/share/mpris-rpc/easyrp" ]]; then
+        if [[ ! -f "$ERP_DIR/easyrp" ]]; then
             echo "EasyRP download failed!"
             exit 1
         else
-            chmod +x "$HOME"/.local/share/mpris-rpc/easyrp
+            chmod +x "$ERP_DIR"/easyrp
         fi
     fi
 }
@@ -89,7 +89,7 @@ case "$1" in
             mprisrpcstart & disown
             cd "$ERP_DIR"
             rm -f "$ERP_DIR"/nohup.out
-            LD_LINUX_LOC="$(ldd ~/.local/share/mpris-rpc/easyrp | grep 'ld-linux' | awk '{print $3}')"
+            LD_LINUX_LOC="$(ldd $ERP_DIR/easyrp | grep 'ld-linux' | awk '{print $3}')"
             case "$LD_LINUX_LOC" in
                 /*) $LD_LINUX_LOC ./easyrp >& ./nohup.out & disown;;
                 *) ./easyrp >& ./nohup.out & disown;;
